### ISSUE TITLE
AV in latest FastMM4-AVX trunk with C++Builder x32 project

### ISSUE THREAD

**Issue by MaxTerentiev** [maximmasiutin/FastMM4-AVX#16] opened 2021-06-18 12:42 UTC
Hi,
I found new problem with latest FastMM4-AVX:

After you fix AV with Delphi x64 project I start getting new AVs with C++Builder x32 project ! It was works fine with previous FastMM-AVX version ! C++Builder x64 project also works fine, so new problem only in x32 mode.

Attached error screenshot and also debugger screenshot with call stack and line number.

![AVScreen](https://user-images.githubusercontent.com/15716038/122562198-7a6cb000-d04b-11eb-9a51-f9c8d878794a.jpg)
![Debugger](https://user-images.githubusercontent.com/15716038/122562202-7e003700-d04b-11eb-90d5-6e06e6b02fb0.jpg)

**Comment by MaxTerentiev** [comment] 2021-06-18 12:59
I also get "Invalid floating point operation" error time to time and debugger stops at this line (see attached screenshot). This happens also with Delphi/CBuilder x32 projects and works fine with Delphi/CBuilder x64. This happens then I close TDBISAMTable. Because its commercial component - I can't publish example project in public (but can send directly to you somehow as .dcu's).

![Debugger1](https://user-images.githubusercontent.com/15716038/122564212-c28cd200-d04d-11eb-935b-8b4ccd4aac67.jpg)

**Comment by maximmasiutin** [comment] 2021-06-18 14:17
Thank you! I will take care of this.

**Comment by maximmasiutin** [comment] 2021-06-18 15:57
What was the commit date of the last version that worked?

**Comment by MaxTerentiev** [comment] 2021-06-18 18:45
Last version fully working in both x32 and x64 in delphi and bcb attached.
[FastMM4.zip](https://github.com/maximmasiutin/FastMM4-AVX/files/6678786/FastMM4.zip)

**Comment by maximmasiutin** [comment] 2021-06-22 19:06
Fixed in the recent commit, thank you!

**Comment by maximmasiutin** [comment] 2021-06-22 19:07
This is the commit that fixes it: 21b9838406c57b92505213546634dd686f868c50

**Closed** 2021-06-22 19:06 UTC

**Comment by maximmasiutin** [comment] 2021-06-22 19:15
The error was caused by improper handling of 8-byte alignment. You can specify 16-byte or 32-byte alignment to fix this problem without even taking the previous commit. Sorry for that!
